// <auto-generated />
using GoodHamburger.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburger.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424220445_AjustaRelacionamentoPedidoProduto")]
    partial class AjustaRelacionamentoPedidoProduto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Sanduiche",
                            Nome = "X Burger",
                            Preco = 5.00m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Sanduiche",
                            Nome = "X Egg",
                            Preco = 4.50m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Sanduiche",
                            Nome = "X Bacon",
                            Preco = 7.00m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "BatataFrita",
                            Nome = "Batata frita",
                            Preco = 2.00m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Refrigerante",
                            Nome = "Refrigerante",
                            Preco = 2.50m
                        });
                });

            modelBuilder.Entity("PedidoProduto", b =>
                {
                    b.Property<int>("ItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemsId", "PedidoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoProdutos", (string)null);
                });

            modelBuilder.Entity("PedidoProduto", b =>
                {
                    b.HasOne("GoodHamburger.Domain.Entities.Produto", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoodHamburger.Domain.Entities.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
